# ansible-playbook inode_monitor.yml -i vendor/ec2.py -vvvv --ask-vault-pass
- name: Add inode monitoring to servers
  hosts: "{{ target_hosts | default('tag_class_app:&tag_app_environment_staging:&tag_app_name_insurance')}}"
  become: true
  user: ubuntu
  vars_files:
    - vault.yml
    - vars.yml
  tasks:
   - name: Install inode monitor on server
     git:
       repo: https://github.com/Foild/newrelic-inode-plugin.git
       dest: /usr/local/bin/newrelic-inode-plugin
       force: yes

   - command: bundle install
     args:
       chdir: /usr/local/bin/newrelic-inode-plugin

   - file:
       src: /usr/local/bin/newrelic-inode-plugin/config/template_newrelic_plugin.yml
       dest: /usr/local/bin/newrelic-inode-plugin/config/newrelic_plugin.yml
       state: link

   - set_fact:
       inode_plugin_host_name: "{{ hostvars[inventory_hostname]['ec2_tag_app_name'] }}-{{ hostvars[inventory_hostname]['ec2_tag_app_environment'] }}-{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

   - lineinfile:
       dest: /usr/local/bin/newrelic-inode-plugin/config/newrelic_plugin.yml
       regexp: '^.*license_key\:.*$'
       line: "  license_key: {{ secrets.newrelic.license }}"

   - lineinfile:
       dest: /usr/local/bin/newrelic-inode-plugin/config/newrelic_plugin.yml
       regexp: '^.*hostname:.*$'
       line: "    hostname: {{ inode_plugin_host_name }}"

   - template:
       src: trusty_newrelic_inode_agent.conf
       dest: /etc/init/newrelic_inode_agent.conf
     when: ansible_distribution_release == 'trusty'

   - template:
       src: xenial_newrelic_inode_agent.conf
       dest: /lib/systemd/system/newrelic_inode_agent.service
     when: ansible_distribution_release == 'xenial'

   - name: Set the service for xenial servers
     command: systemctl daemon-reload
     when: ansible_distribution_release == 'xenial'

   - name: Set the service for xenial servers
     command: systemctl enable newrelic_inode_agent.service
     when: ansible_distribution_release == 'xenial'

   - service:
       name: newrelic_inode_agent
       state: started
